Various improvements
Yorwba/anki-wikidata-geography pull request #6
Opened 2021-10-25 20:37 UTC by zserghei

2021-11-01 19:15 UTC, Yorwba commented
Thank you for splitting up the PR into multiple commits, and sorry for taking so long to review. I like your changes overall, but I have some small nitpicks to point out.

2021-11-01 19:41 UTC, Yorwba requested changes

2021-11-01 19:41 UTC, Yorwba commented on build_deck.py
> +IMAGE_FOLDER = "img"
Could you make this configurable as a command-line parameter? Maybe even default to a temporary folder so the files don't keep lying around after building the deck.

2021-11-01 19:41 UTC, Yorwba commented on build_deck.py
> +logger.setLevel(logging.DEBUG)
Would be nice to have the loglevel configurable, too.

2021-11-01 19:41 UTC, Yorwba commented on build_deck.py
> +from os.path import exists
It's a bit weird to import `exists` in this commit when you're only using it much later in 30d8b35, but I'll let it slide.

2021-11-01 19:41 UTC, Yorwba commented on build_deck.py
> +        return genanki.guid_for(*self.fields[:3])
The purpose of using a custom `guid` is to enable replacing old cards with new versions even if some fields have changed. Changing the implementation after adding fields kind of defeats the point.

2021-11-01 19:41 UTC, Yorwba commented on build_deck.py
> +            = 'AnkiWikidataGeography/1.0 (https://github.com/Yorwba/anki-wikidata-geography) generic-library/1.0'
Thanks for adding this, but I think the `generic-library/1.0` part is only intended as a placeholder in case library versions are relevant.

2021-11-11 21:38 UTC, zserghei commented on build_deck.py
> +IMAGE_FOLDER = "img"
done

2021-11-11 21:38 UTC, zserghei commented on build_deck.py
> +logger.setLevel(logging.DEBUG)
done

2021-11-11 21:38 UTC, zserghei commented on build_deck.py
> +            = 'AnkiWikidataGeography/1.0 (https://github.com/Yorwba/anki-wikidata-geography) generic-library/1.0'
Removed.

2021-11-11 21:44 UTC, zserghei commented on build_deck.py
> +        return genanki.guid_for(*self.fields[:3])
The newly added third field is the capital of the administrative subdivision. It is a significant field and I think that it should be added to the guid calculation for the cards. Otherwise, cards won't be replaced even if the capital name changes. Or did I misunderstood something?

2021-11-21 13:39 UTC, Yorwba commented on build_deck.py
> +        return genanki.guid_for(*self.fields[:3])
The [`genanki` documentation](https://github.com/kerrickstaley/genanki/blob/master/README.md#note-guids) says:
> Notes have a guid property that uniquely identifies the note. If you import a new note that has the same GUID as an existing note, the new note will overwrite the old one (as long as their models have the same fields).

So if you add the capital name to the guid calculation and the capital name changes, the guid will change as well and the old card **won't** be replaced.

But good point about names changing. The guid should probably just depend on the Wikidata ID, since all other fields are subject to change.

2021-11-21 13:47 UTC, Yorwba reviewed
Thank you for the changes! I think the `guid` is quite important to get right, but I'll leave it up to you whether you want to rewrite the temporary folder thing.

2021-11-21 13:47 UTC, Yorwba commented on build_deck.py
> +    parser.add_argument('--image-folder', default='/tmp', help="Folder to store temporary images, '/tmp' by default")
I was thinking more along the lines of using `tempfile.TemporaryDirectory`, which has the added benefit of automatically cleaning up all files if you use it as a context manager.

2021-12-28 22:10 UTC, zserghei commented on build_deck.py
> +        return genanki.guid_for(*self.fields[:3])
Done.

2021-12-28 22:10 UTC, zserghei commented on build_deck.py
> +    parser.add_argument('--image-folder', default='/tmp', help="Folder to store temporary images, '/tmp' by default")
Done.

2021-12-28 22:12 UTC, zserghei commented
@Yorwba All requested changes are implemented. Please, review.

2022-01-21 20:36 UTC, merged

2022-01-21 20:40 UTC, Yorwba commented
@zserghei Thanks a lot for your work and sorry for making you wait so long again! There's one small thing which I don't quite like, namely your change from
```
return genanki.guid_for(*self.fields[:3])
```
to
```
return genanki.guid_for(*self.fields[5])
```
Which ends up splitting each character of the fifth field into its own parameter for `guid_for`. That's not exactly wrong, but also kind of weird. Rather than make you go through another slow round of corrections, I've decided to merge your PR as-is and remove the `*` myself.

Again, thanks a lot!